### ISSUE TITLE
Upload to AUR

### ISSUE THREAD

**Issue by ava1ar** [jtrefke/dell-e310dw-cups-printer-driver#1]
Hi! 
Thanks for the PKGBUILD! Any reason it is not uploaded to the AUR yet?

**Comment by jtrefke** [comment]
Hi ava1ar,
Thanks for creating the issue. I've uploaded it to the [AUR as "dell-e310dw"](https://aur.archlinux.org/packages/dell-e310dw) as there's no reason (anymore) why it cannot be there.
